a=float(input('enter no a '))
b=float(input('enter no b '))
c=float(input('enter no c '))
d=float(input('enter no d '))
e=float(input('enter no e'))
f=float(input('enter no f '))
g=float(input('enter no g '))
solve = float((a+b/c)/(d+(e/(f+g))))
print(solve)
